-- MySQL Script generated by MySQL Workbench
-- Sat May 25 15:01:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema empenio20190525
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema empenio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empenio
-- -----------------------------------------------------
CREATE DATABASE  IF NOT EXISTS `empenio` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `empenio`;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
 SET NAMES utf8 ;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- -----------------------------------------------------
-- Table `empenio`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`categorias` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `Categorias_idCategoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categorias_Categorias1_idx` (`Categorias_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `empenio`.`categorias` (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Dumping data for table `categorias`
--

LOCK TABLES `categorias` WRITE;
/*!40000 ALTER TABLE `categorias` DISABLE KEYS */;
INSERT INTO `categorias` VALUES (1,'Rol',NULL),(2,'Oro',NULL),(3,'Producto',NULL),(4,'Venta/apartado',NULL),(5,'Periodo',NULL),(6,'Ocupacion',NULL),(7,'Administrador',1),(8,'Cajero',1),(9,'Gerente',1),(10,'Bodeguero',1),(11,'Venta',4),(12,'Apartado',4),(13,'Semanal',5),(14,'Quincenal',5),(15,'Mensual',5),(16,'Maestro',6),(17,'Ingeniero',6),(18,'Ama de casa',6),(19,'Carpitero',6),(20,'Mecanico',6),(22,'Equipo de computo',3),(23,'Videojuegos',3),(24,'Joyería',2);
/*!40000 ALTER TABLE `categorias` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `empenio`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`cliente` (
  `nombre` VARCHAR(30) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `curp` VARCHAR(18) NOT NULL,
  `numeroIdentificacion` VARCHAR(20) NOT NULL,
  `ocupacion` INT(11) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `enListaNegra` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`rfc`),
  INDEX `fk_Cliente_Categorias1_idx` (`ocupacion` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Categorias1`
    FOREIGN KEY (`ocupacion`)
    REFERENCES `empenio`.`categorias` (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Dumping data for table `cliente`
--

LOCK TABLES `cliente` WRITE;
/*!40000 ALTER TABLE `cliente` DISABLE KEYS */;
INSERT INTO `cliente` VALUES ('Cliente no registrado',' ',' ','0000000000000','000000000000000000','1111',20,'2019-05-07',0);
/*!40000 ALTER TABLE `cliente` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `empenio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`usuario` (
  `numPersonal` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(60) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `rol` INT(11) NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `deBaja` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`numPersonal`),
  INDEX `fk_Usuario_Categorias1_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Categorias1`
    FOREIGN KEY (`rol`)
    REFERENCES `empenio`.`categorias` (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `usuario` WRITE;
/*!40000 ALTER TABLE `usuario` DISABLE KEYS */;
INSERT INTO `usuario` VALUES (0,'Usuario default','root',7,'2019-05-09',0);
/*!40000 ALTER TABLE `usuario` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `empenio`.`ventaapartado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`ventaapartado` (
  `idVentaApartado` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `Cliente_rfc` VARCHAR(13) NOT NULL,
  `Usuario_numPersonal` INT(11) NOT NULL,
  `tipoVenta` INT(11) NOT NULL,
  PRIMARY KEY (`idVentaApartado`),
  INDEX `fk_VentaApartado_Cliente1_idx` (`Cliente_rfc` ASC) VISIBLE,
  INDEX `fk_VentaApartado_Usuario1_idx` (`Usuario_numPersonal` ASC) VISIBLE,
  INDEX `fk_VentaApartado_Categorias1_idx` (`tipoVenta` ASC) VISIBLE,
  CONSTRAINT `fk_VentaApartado_Categorias1`
    FOREIGN KEY (`tipoVenta`)
    REFERENCES `empenio`.`categorias` (`idCategoria`),
  CONSTRAINT `fk_VentaApartado_Cliente1`
    FOREIGN KEY (`Cliente_rfc`)
    REFERENCES `empenio`.`cliente` (`rfc`),
  CONSTRAINT `fk_VentaApartado_Usuario1`
    FOREIGN KEY (`Usuario_numPersonal`)
    REFERENCES `empenio`.`usuario` (`numPersonal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `empenio`.`adelantoapartado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`adelantoapartado` (
  `idadelantoapartado` INT(11) NOT NULL,
  `monto` INT(11) NOT NULL,
  `idVentaApartado` INT(11) NOT NULL,
  PRIMARY KEY (`idadelantoapartado`),
  INDEX `idVentaApartado_idx` (`idVentaApartado` ASC) VISIBLE,
  CONSTRAINT `idVentaApartado`
    FOREIGN KEY (`idVentaApartado`)
    REFERENCES `empenio`.`ventaapartado` (`idVentaApartado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `empenio`.`comercializacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`comercializacion` (
  `idComercializacion` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_numPersonal` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idComercializacion`),
  INDEX `fk_Comercializacion_Usuario1_idx` (`Usuario_numPersonal` ASC) VISIBLE,
  CONSTRAINT `fk_Comercializacion_Usuario1`
    FOREIGN KEY (`Usuario_numPersonal`)
    REFERENCES `empenio`.`usuario` (`numPersonal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Dumping data for table `comercializacion`
--

LOCK TABLES `comercializacion` WRITE;
/*!40000 ALTER TABLE `comercializacion` DISABLE KEYS */;
INSERT INTO `comercializacion` VALUES (0,0,'2019-05-19');
/*!40000 ALTER TABLE `comercializacion` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `empenio`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`contrato` (
  `idContrato` INT(11) NOT NULL AUTO_INCREMENT,
  `Cliente_rfc` VARCHAR(13) NOT NULL,
  `Usuario_numPersonal` INT(11) NOT NULL,
  `interesOrdinario` INT(11) NOT NULL,
  `interesAlmacen` INT(11) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  PRIMARY KEY (`idContrato`),
  INDEX `fk_Contrato_Cliente1_idx` (`Cliente_rfc` ASC) VISIBLE,
  INDEX `fk_Contrato_Usuario1_idx` (`Usuario_numPersonal` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Cliente1`
    FOREIGN KEY (`Cliente_rfc`)
    REFERENCES `empenio`.`cliente` (`rfc`),
  CONSTRAINT `fk_Contrato_Usuario1`
    FOREIGN KEY (`Usuario_numPersonal`)
    REFERENCES `empenio`.`usuario` (`numPersonal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Dumping data for table `contrato`
--

LOCK TABLES `contrato` WRITE;
/*!40000 ALTER TABLE `contrato` DISABLE KEYS */;
INSERT INTO `contrato` VALUES (0,'0000000000000',0,8,2,'2018-05-20','2018-06-20');
/*!40000 ALTER TABLE `contrato` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `empenio`.`prenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`prenda` (
  `descripcion` VARCHAR(120) NOT NULL,
  `avaluo` INT(11) NOT NULL,
  `prestamo` INT(11) NOT NULL,
  `idPrenda` INT(11) NOT NULL AUTO_INCREMENT,
  `Contrato_idContrato` INT(11) NOT NULL,
  `categoria` INT(11) NOT NULL,
  `tipoProducto` INT(11) NOT NULL,
  PRIMARY KEY (`idPrenda`),
  INDEX `fk_Prenda_Contrato1_idx` (`Contrato_idContrato` ASC) VISIBLE,
  INDEX `fk_Prenda_Categorias1_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_Prenda_Categorias2_idx` (`tipoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Prenda_Categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `empenio`.`categorias` (`idCategoria`),
  CONSTRAINT `fk_Prenda_Categorias2`
    FOREIGN KEY (`tipoProducto`)
    REFERENCES `empenio`.`categorias` (`idCategoria`),
  CONSTRAINT `fk_Prenda_Contrato1`
    FOREIGN KEY (`Contrato_idContrato`)
    REFERENCES `empenio`.`contrato` (`idContrato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Dumping data for table `prenda`
--

LOCK TABLES `prenda` WRITE;
/*!40000 ALTER TABLE `prenda` DISABLE KEYS */;
INSERT INTO `prenda` VALUES ('Prenda de prueba',2500,1800,0,0,3,22);
/*!40000 ALTER TABLE `prenda` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `empenio`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`articulo` (
  `idArticulo` INT(11) NOT NULL AUTO_INCREMENT,
  `prenda_idPrenda` INT(11) NOT NULL,
  `categoria` INT(11) NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  `precio` INT(11) NOT NULL,
  `comercializacion_idComercializacion` INT(11) NOT NULL,
  `tipoProducto` INT(11) NOT NULL,
  `deBaja` TINYINT(4) NOT NULL DEFAULT '0',
  `vendido` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_Articulo_Prenda1_idx` (`prenda_idPrenda` ASC) VISIBLE,
  INDEX `fk_Articulo_Categorias1_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_Articulo_Comercializacion_idx` (`comercializacion_idComercializacion` ASC) VISIBLE,
  INDEX `fk_Articulo_Categorias2_idx` (`tipoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Articulo_Categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `empenio`.`categorias` (`idCategoria`),
  CONSTRAINT `fk_Articulo_Categorias2`
    FOREIGN KEY (`tipoProducto`)
    REFERENCES `empenio`.`categorias` (`idCategoria`),
  CONSTRAINT `fk_Articulo_Comercializacion`
    FOREIGN KEY (`comercializacion_idComercializacion`)
    REFERENCES `empenio`.`comercializacion` (`idComercializacion`),
  CONSTRAINT `fk_Articulo_Prenda1`
    FOREIGN KEY (`prenda_idPrenda`)
    REFERENCES `empenio`.`prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Dumping data for table `articulo`
--

LOCK TABLES `articulo` WRITE;
/*!40000 ALTER TABLE `articulo` DISABLE KEYS */;
INSERT INTO `articulo` VALUES (0,0,3,'Artículo de prueba',300000,0,22,0,0);
/*!40000 ALTER TABLE `articulo` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `empenio`.`fotocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`fotocliente` (
  `idfotoCliente` INT(11) NOT NULL,
  `Cliente_rfc` VARCHAR(13) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfotoCliente`),
  INDEX `fk_fotoCliente_Cliente1_idx` (`Cliente_rfc` ASC) VISIBLE,
  CONSTRAINT `fk_fotoCliente_Cliente1`
    FOREIGN KEY (`Cliente_rfc`)
    REFERENCES `empenio`.`cliente` (`rfc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `empenio`.`fotocontrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`fotocontrato` (
  `idfotoContrato` INT(11) NOT NULL AUTO_INCREMENT,
  `Contrato_idContrato` INT(11) NOT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfotoContrato`),
  INDEX `fk_fotoContrato_Contrato1_idx` (`Contrato_idContrato` ASC) VISIBLE,
  CONSTRAINT `fk_fotoContrato_Contrato1`
    FOREIGN KEY (`Contrato_idContrato`)
    REFERENCES `empenio`.`contrato` (`idContrato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `empenio`.`parametrossucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`parametrossucursal` (
  `idSucursal` INT(11) NOT NULL AUTO_INCREMENT,
  `fondo` INT(11) NOT NULL,
  `interesOrdinario` INT(11) NOT NULL,
  `interesAlmacen` INT(11) NOT NULL,
  `tipoPeriodo` INT(11) NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_ParametrosSucursal_Categorias1_idx` (`tipoPeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_ParametrosSucursal_Categorias1`
    FOREIGN KEY (`tipoPeriodo`)
    REFERENCES `empenio`.`categorias` (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `parametrossucursal` WRITE;
/*!40000 ALTER TABLE `parametrossucursal` DISABLE KEYS */;
INSERT INTO `parametrossucursal` VALUES (1,8000000,8,5,14);
/*!40000 ALTER TABLE `parametrossucursal` ENABLE KEYS */;
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `empenio`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`periodo` (
  `idPeriodo` INT(11) NOT NULL AUTO_INCREMENT,
  `Contrato_idContrato` INT(11) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `montoRefrendo` INT(11) NOT NULL,
  `tipoPeriodo` INT(11) NOT NULL,
  `montoFiniquito` INT(11) NOT NULL,
  PRIMARY KEY (`idPeriodo`),
  INDEX `fk_Periodo_Contrato1_idx` (`Contrato_idContrato` ASC) VISIBLE,
  INDEX `fk_Periodo_Categorias1_idx` (`tipoPeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_Periodo_Categorias1`
    FOREIGN KEY (`tipoPeriodo`)
    REFERENCES `empenio`.`categorias` (`idCategoria`),
  CONSTRAINT `fk_Periodo_Contrato1`
    FOREIGN KEY (`Contrato_idContrato`)
    REFERENCES `empenio`.`contrato` (`idContrato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `empenio`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`ticket` (
  `VentaApartado` INT(11) NOT NULL,
  `Articulo_idArticulo` INT(11) NOT NULL,
  INDEX `fk_VentaApartado_has_Articulo_Articulo1_idx` (`Articulo_idArticulo` ASC) VISIBLE,
  INDEX `fk_VentaApartado_has_Articulo_VentaApartado1_idx` (`VentaApartado` ASC) VISIBLE,
  CONSTRAINT `fk_VentaApartado_has_Articulo_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `empenio`.`articulo` (`idArticulo`),
  CONSTRAINT `fk_VentaApartado_has_Articulo_VentaApartado1`
    FOREIGN KEY (`VentaApartado`)
    REFERENCES `empenio`.`ventaapartado` (`idVentaApartado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `empenio`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empenio`.`Pago` (
  `idPago` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaLimite` DATE NOT NULL,
  `contrato_idContrato` INT(11) NOT NULL,
  PRIMARY KEY (`idPago`, `fechaInicio`),
  INDEX `fk_Pago_contrato1_idx` (`contrato_idContrato` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_contrato1`
    FOREIGN KEY (`contrato_idContrato`)
    REFERENCES `empenio`.`contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
